# Generated by Django 4.0.2 on 2022-02-14 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0002_product_image_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(default='', max_length=100),
        ),
    ]
